import numpy as np
import pandas as pd

df = pd.read_csv("BRFSS_2015ver10.csv")


cols = [
    'GENHLTH', 'PHYSHLTH', 'MENTHLTH', 'POORHLTH', 'HLTHPLN1', 'PERSDOC2', 'MEDCOST', 'CHECKUP1', 'BPMEDS', 'BLOODCHO',
    'CHOLCHK', 'TOLDHI2', 'CVDINFR4', 'ASTHMA3', 'ASTHNOW', 'CHCSCNCR', 'CHCOCNCR', 'CHCCOPD1',
    'HAVARTH3',
    'ADDEPEV2', 'MARITAL', 'EDUCA', 'RENTHOM1', 'VETERAN3', 'EMPLOY1', 'INCOME2', 'INTERNET', 'QLACTLM2', 'USEEQUIP',
    'DECIDE', 'DIFFWALK', 'DIFFDRES', 'DIFFALON', 'SMOKE100', 'STOPSMK2', 'LASTSMK2', 'USENOW3', 'LMTJOIN3', 'ARTHDIS2',
    'ARTHSOCL', 'JOINPAIN', 'FLUSHOT6', 'PNEUVAC3', 'HIVTST6', 'HIVTSTD3', 'WHRTST10', 'PDIABTST', 'PREDIAB1', 'INSULIN',
    'BLDSUGAR', 'FEETCHK2', 'DOCTDIAB', 'CHKHEMO3', 'FEETCHK', 'DIABEYE', 'CIMEMLOS', 'SXORIENT', 'TRNSGNDR', 'MSCODE',
    '_RFHLTH', '_HCVU651', '_CHOLCHK', '_RFCHOL', '_LTASTH1', '_CASTHM1', '_ASTHMS1', '_DRDXAR1', '_MRACE1', '_HISPANC',
    '_RACE', '_RACEG21', '_INCOMG', 'FC60_', '_PASTAE1', '_FLSHOT6', '_PNEUMO2', '_AIDTST3', 'EXRACT11', 'EXEROFT1',
    'EXERHMM1', 'EXRACT21', 'EXEROFT2', 'EXERHMM2', 'DRNK3GE5', '_RFBING5', '_DRNKWEK', '_RFDRHV5', 'FTJUDA1_', 'FRUTDA1_',
    'BEANDAY_', 'GRENDAY_', 'ORNGDAY_', 'VEGEDA1_', '_FRUTSUM', '_VEGESUM', '_FRTLT1', '_VEGLT1', 'ACTIN11_', 'ACTIN21_',
    'PADUR1_', 'PADUR2_', 'PAFREQ1_', 'PAFREQ2_', '_MINAC11', '_MINAC21', 'STRFREQ_', 'PAMIN11_', 'PAMIN21_', 'PAVIG11_',
    'PAVIG21_', '_PAINDX1', '_PA300R2', '_PASTRNG', '_PAREC1', '_BMI5CAT', '_PA150R2', 'BPHIGH4', 'CVDCRHD4', 'CVDSTRK3',
    'CHCKIDNY', 'DIABETE3', 'SEX', 'PREGNANT', 'SMOKDAY2', 'ALCDAY5', 'AVEDRNK2', 'MAXDRNKS', 'FRUITJU1', 'FRUIT1',
    'FVBEANS', 'FVGREEN', 'FVORANG', 'VEGETAB1', 'EXERANY2', 'STRENGTH', '_RFHYPE5', '_MICHD', 'HTM4', 'WTKG3', '_BMI5',
    '_SMOKER3', 'DRNKANY5', 'DROCDY3_', '_FRUITEX', '_VEGETEX', '_PACAT1', '_AGEG5YR',
]

# 빈칸을 NaN으로 변경
df[cols] = df[cols].replace(r'^\s*$', np.nan, regex=True)

df.to_csv("BRFSS_2015ver11.csv", index=False)